services:
  backend:
    build:
      context: ../backend
      # dockerfile: Dockerfile
      dockerfile: Dockerfile.dev
    ports:
      - "5000:5000"
    working_dir: /app
    env_file:
      - ../backend/.env
    # chay development
    volumes:
      - ../backend:/app
    # depends_on:
    #   - mongodb
    restart: on-failure
    command: npm run dev
    # command: npm run start
  frontend:
    build: ../admin-html
    ports:
      - "5500:80"
    volumes:
      - ../admin-html:/usr/share/nginx/html:ro
    restart: unless-stopped


  # frontend_flutter:
  #   build:
  #     context: ../frontend
  #     dockerfile: Dockerfile
  #   working_dir: /app
  #   volumes:
  #     - ./flutter-output:/output
  #   restart: on-failure

  # mongodb:
  #   image: mongo:latest
  #   ports:
  #     - "27017:27017"
  #   volumes:
  #     - mongo-data:/data/db
  #   restart: unless-stopped

# volumes:
#   mongo-data:
