services:
  backend:
    build:
      context: ../backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ../backend:/app
      - /app/node_modules
    env_file:
      - ../backend/.env
    depends_on:
      - mongodb
    restart: on-failure
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data: