version: "3.9"

services:
  backend:
    build:
      context: ../backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ../backend:/app
      - /app/node_modules
    working_dir: /app
    env_file:
      - ../backend/.env
    depends_on:
      - mongodb
    restart: on-failure
    command: npm run dev

  frontend_admin:
    build:
      context: ../frontend-admin
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - ../frontend-admin:/app
      - /app/node_modules
    working_dir: /app
    env_file:
      - ../frontend-admin/.env
    depends_on:
      - backend
    restart: on-failure
    command: npm run dev

  frontend_flutter:
    image: ghcr.io/cirruslabs/flutter:stable
    build:
      context: ../frontend
      dockerfile: Dockerfile
    working_dir: /app
    volumes:
      - ../frontend-flutter:/app
      - ./flutter-output:/output
    command: flutter build apk --release
    restart: on-failure

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    restart: unless-stopped

volumes:
  mongo-data:
