services:
  backend:
    build:
      context: ../backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    working_dir: /app
    env_file:
      - ../backend/.env
    # depends_on:
    #   - mongodb
    restart: on-failure
    command: npm run dev

  admin-dashboard:
    build:
      context: ../admin-dashboard
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    working_dir: /app
    env_file:
      - ../admin-dashboard/.env
    depends_on:
      - backend
    restart: on-failure
    command: npm run dev

  # frontend_flutter:
  #   build:
  #     context: ../frontend
  #     dockerfile: Dockerfile
  #   working_dir: /app
  #   volumes:
  #     - ./flutter-output:/output
  #   restart: on-failure

#   mongodb:
#     image: mongo:latest
#     ports:
#       - "27017:27017"
#     volumes:
#       - mongo-data:/data/db
#     restart: unless-stopped

# volumes:
#   mongo-data:
