openapi: 3.0.0
info:
  title: API Documentation
  version: 1.0.0
servers:
  - url: http://localhost:3000/api

paths:
  /admin:
    $ref: './swagger/admin.yaml#/paths'
  /auth:
    $ref: './swagger/auth.yaml#/paths'
  /banner:
    $ref: './swagger/banner.yaml#/paths'
  /booking:
    $ref: './swagger/booking.yaml#/paths'
  /location:
    $ref: './swagger/location.yaml#/paths'
  /payment:
    $ref: './swagger/payment.yaml#/paths'
  /review:
    $ref: './swagger/review.yaml#/paths'
  /user:
    $ref: './swagger/user.yaml#/paths'
  /vehicle:
    $ref: './swagger/vehicle.yaml#/paths'

