openapi: 3.0.0
info:
  title: API Documentation
  version: 1.0.0
servers:
  - url: http://localhost:3000/api

paths:
  /admin:
    $ref: './swagger/admin.yaml#/paths/~1admin'
  
  /auth:
    $ref: './swagger/auth.yaml#/paths/~1auth'

  /banner:
    $ref: './swagger/banner.yaml#/paths/~1banner'

  /booking:
    $ref: './swagger/booking.yaml#/paths/~1booking'

  /location:
    $ref: './swagger/location.yaml#/paths/~1location'

  /payment:
    $ref: './swagger/payment.yaml#/paths/~1payment'

  /review:
    $ref: './swagger/review.yaml#/paths/~1review'

  /user:
    $ref: './swagger/user.yaml#/paths/~1user'

  /vehicle:
    $ref: './swagger/vehicle.yaml#/paths/~1vehicle'
